### ISSUE TITLE
External syntax

### ISSUE THREAD

**Issue by subhero24** [FlorianRappl/parcel-plugin-externals#1]
Any reason the externals value has custom syntax with '=>' instead of an object? Would prefer something like this

```json
{
  "externals": {
    "react": "React"
  }
}
```

over 

```json
{
  "externals": [
    "react => React"
  ]
}
```

**Comment by FlorianRappl** [comment]
I think we can go for both.

I introduced this syntax to make it optional, e.g., using

```json
{
  "externals": [
    "react"
  ]
}
```

is valid, too. This could be interesting if React is / should not be a peer dependency, but desired as an external (but with the default fallback to `require('react')`.

I would introduce the alternative with an object which will be converted respectively (`${key} => ${value}`).

How does that sound?

cc @subhero24

**Comment by subhero24** [comment]
I am all in favor of supporting both object- and array-style externals. But I find the custom syntax with '=>' to map a value to something else a bit unnecessary, as we already have objects to map a value to another.

**Comment by FlorianRappl** [comment]
> I am all in favor of supporting both object- and array-style externals. But I find the custom syntax with '=>' to map a value to something else a bit unnecessary, as we already have objects to map a value to another.

True but we require a string representation for handing that over internally. This string representation is the direct consequence. In my opinion its fairly straight forward to understand.

I agree with the clarity of the object representation though. It's a good call :beers:!

**Comment by FlorianRappl** [comment]
I published a preview version. Let me know if it works as expected / any other things to improve.

https://www.npmjs.com/package/parcel-plugin-externals/v/0.2.0-pre.20191021.1

cc @subhero24
