### ISSUE TITLE
Use @parcel/logger instead of console

### ISSUE THREAD

**Issue by 101arrowz** [FlorianRappl/parcel-plugin-externals#21]
[As I use in my own plugin](https://github.com/101arrowz/pwa-manifest/blob/master/packages/parcel-plugin-pwa-manifest/index.ts#L3), there is a package `@parcel/logger` that integrates directly with Parcel's logging system. I would suggest using it instead of `console` because it looks much cleaner (you can install that plugin to see for yourself). You could also throw errors for prettier output than `console.error`.

I have a [declaration file](https://github.com/101arrowz/pwa-manifest/blob/master/packages/parcel-plugin-pwa-manifest/types/parcel__logger.d.ts) for `@parcel/logger`, which should give you a general sense of its API.

**Comment by FlorianRappl** [comment]
Mind doing a PR?

(you should be well aware that I know the parcel logger very well incl. some of its bugs and edge cases)
