### ISSUE TITLE
How to make dependencies with slash "/" as external?

### ISSUE THREAD

**Issue by djalmajr** [FlorianRappl/parcel-plugin-externals#7]
How to make dependencies like lodash/fp as external?

A single call to lodash/fp makes the bundle size larger.

![image](https://user-images.githubusercontent.com/1858147/68787208-dc6b6500-061f-11ea-9ec6-bfca78e45495.png)

Removing it, the size get smaller.

![image](https://user-images.githubusercontent.com/1858147/68787470-5f8cbb00-0620-11ea-9837-4f14d0e4b6fc.png)

**Comment by djalmajr** [comment]
As workaround, I had to do this:

#### `package.json`
```javascript
{
  ...
  "externals": "./externals.cfg.js"
}
```

#### `externals.cfg.js`
```javascript
const rx = /node_modules\/lodash(\/.*).js/;

module.exports = function (path) {
  const result = rx.exec(path);

  if (result) {
    const suffix = result[1].replace('/lodash', '');
    const name = suffix.replace('/', '') || '_';
    return `lodash${suffix} => ${name}`; // return "lodash => _" or "lodash/fp => fp"
  }

  return undefined;
};
```

Would be nice if I can use like this:

#### `package.json`
```javascript
{
  ...
  "externals": {
    "lodash": "_",
    "lodash/fp": "fp"
  }
}
```

**Comment by FlorianRappl** [comment]
I'm not sure yet when I can deal with this. I think I'll give it a shot on Friday, but if you manage to look at the source / do a PR in the meantime it would be superb.

Thanks for showing the workaround and raising the issue! :beers:

**Comment by FlorianRappl** [comment]
Is in the 0.3! Hope it works and sorry for the delay @djalmajr !
